version: '2'

services:
    symfony5:
        container_name: '${SITE_NAME_INTERNAL}_symfony5'
        image: 'wexample/symfony5:${WEX_IMAGES_VERSION}'
        stdin_open: true
        tty: true
        restart: always
        expose:
            - 80
        environment:
            - WEX_SITE_ENV=${SITE_ENV}
            - VIRTUAL_HOST=${DOMAIN_MAIN}
            - VIRTUAL_PORT=80
            # Database
            - MYSQL_DB_HOST=${MYSQL_DB_HOST}
            - MYSQL_DB_NAME=${MYSQL_DB_NAME}
            - MYSQL_DB_USER=${MYSQL_DB_USER}
            - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
        volumes:
            # Site folder
            - ${SITE_PATH_ROOT}:/var/www/html
            # Apache
            - ${CONF_WEB_APACHE_CONF}:/etc/apache2/sites-available/000-default.conf
            # Php
            - ${CONF_WEB_PHP_INI}:/etc/php/8.1/fpm/conf.d/99-wex.ini
            - ${CONF_WEB_PHP_INI}:/etc/php/8.1/cli/conf.d/99-wex.ini
            # Mysql dumps
            - ${SITE_PATH_ROOT}mysql/dumps:/var/www/mysql/dumps
            # Share same wex scripts for all environments.
            - ${WEX_SCRIPTS_PATH}:/opt/wexample
            # Use common certificates storage
            - ${WEX_WEXAMPLE_DIR_PROXY}proxy/certs:/certs
            # Cron management
            - ${SITE_PATH_ROOT}cron/${SITE_ENV}:/var/default.cron
        networks:
            - tmp_wex_net

