docker:
  compose:
    stdin_open: true
    tty: true
  main_container: dev
env:
  dev:
    email: contact@wexample.com
  local:
    email: contact@wexample.com
  prod:
    email: contact@wexample.com
global:
  author: root
  created: '2023-03-23 17:13:28'
  name: wex
  services: []
  type: app
  version: 5.0.109+build.20231222121004
wex:
  version: 5.0.109+build.20231222121004
