version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy:0.7.0
    container_name: ${SITE_NAME}
    volumes:
      # Nginx configuration
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${SITE_PATH_ROOT}proxy/certs:/etc/nginx/certs:ro
      - ${SITE_PATH_ROOT}proxy/vhost.d:/etc/nginx/vhost.d
      - ${SITE_PATH_ROOT}proxy/html:/usr/share/nginx/html
      - ${SITE_PATH_ROOT}proxy/logs:/var/log/nginx
      - ${SITE_PATH_ROOT}proxy/wex.conf:/etc/nginx/conf.d/wex.conf
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: nginx_proxy
    restart: always
    privileged: true
    networks:
      - wex_net

  certs:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.8.1
    container_name: ${SITE_NAME}_certs
    volumes:
      - ${SITE_PATH_ROOT}proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

# TODO Run it in production only, if expected by at least one app
#  ftp:
#    image: wexample/ftp
#    container_name: ${SITE_NAME}_ftp
#    environment:
#      - PUBLICHOST=${SERVER_IP}
#      - PORTS_RANGE=30000:30059
#    volumes:
#      # Share all sites
#      - /var/www:/var/www
#      # Store passwords in the same place
#      - ${SITE_PATH_ROOT}proxy/ftp/passwd:/etc/pure-ftpd/passwd
#    networks:
#      - wex_net